import uuid

from fastapi import FastAPI, File, Request, UploadFile
from fastapi.responses import HTMLResponse
from fastapi.templating import Jinja2Templates

import plotly.io as pio

import processor

try:
    from charts import getCharts
except ImportError:
    import plotly.graph_objects as go

    def getCharts(data, game, player):
        fig = go.Figure()
        fig.add_annotation(
            text="charts.py not found — plug in getCharts()",
            xref="paper", yref="paper", x=0.5, y=0.5, showarrow=False,
        )
        fig.update_layout(height=300, template="plotly_dark")
        return [fig]

app = FastAPI()
templates = Jinja2Templates(directory="templates")

SESSIONS: dict[str, dict] = {}

def render_plotly(fig) -> str:
    return pio.to_html(
        fig,
        full_html=False,
        include_plotlyjs=False,
        config={"responsive": True, "displayModeBar": False},
    )

def render_stats(title, stats):
    if not stats:
        return f'<h2 class="view-title">{title}</h2>'

    def stat(label, value):
        return f"""
        <div class="stat-cell">
            <div class="stat-value">{value}</div>
            <div class="stat-label">{label}</div>
        </div>"""

    return f"""
    <div class="stats-bar">
        <h2 class="view-title">{title}</h2>
        <div class="stat-groups">
            <div class="stat-group">
                <div class="stat-group-label">THROWING</div>
                <div class="stat-cells">
                    {stat("COMP %",      f'{stats["comp_pct"]}%')}
                    {stat("COMPLETIONS", stats["completions"])}
                    {stat("THROWAWAYS",  stats["throwaways"])}
                    {stat("ASSISTS",     stats["assists"])}
                    {stat("YARDS",       stats["throw_yards"])}
                </div>
            </div>
            <div class="stat-divider"></div>
            <div class="stat-group">
                <div class="stat-group-label">RECEIVING</div>
                <div class="stat-cells">
                    {stat("CATCH %",    f'{stats["catch_pct"]}%')}
                    {stat("RECEPTIONS", stats["receptions"])}
                    {stat("DROPS",      stats["drops"])}
                    {stat("GOALS",      stats["goals"])}
                    {stat("YARDS",      stats["recep_yards"])}
                </div>
            </div>
        </div>
    </div>
    """

@app.get("/", response_class=HTMLResponse)
async def index(request: Request):
    return templates.TemplateResponse("index.html", {"request": request})


@app.post("/upload", response_class=HTMLResponse)
async def upload(files: list[UploadFile] = File(...)):
    file_list = [(f.filename or "unknown", await f.read()) for f in files]
    data, warnings = processor.processUploads(file_list)

    session_id = str(uuid.uuid4())
    SESSIONS[session_id] = data

    games   = processor.getGameList(data)
    players = processor.getPlayerList(data)

    return HTMLResponse(
        sidebar_html(
            session_id=session_id,
            games=games,
            players=players,
            warnings=warnings,
            active_game="All",
            active_player="Team",
        )
    )

# route uses query params [ ?game=X&player=Y ] to match URLs generated by HTMX below.
@app.get("/charts/{session_id}", response_class=HTMLResponse)
async def charts_view(session_id: str, game: str = "All", player: str = "Team"):
    data = SESSIONS.get(session_id)
    if data is None:
        return HTMLResponse('<p class="error-msg">Session expired. Re-upload files.</p>')

    games   = processor.getGameList(data)
    players = processor.getPlayerList(data)

    try:
        title, stats, figs = getCharts(data, game, player)
    except Exception as exc:
        charts_html = f'<p class="error-msg">Chart error: {exc}</p>'
    else:
        stats_html = render_stats(title, stats)
        if figs:
            divs = "\n".join(
                f'<div class="chart-wrapper">{render_plotly(f)}</div>'
                for f in figs
            )
            charts_html = stats_html + f'<div class="charts">{divs}</div>'
        else:
            charts_html = stats_html + '<p class="error-msg">No charts returned.</p>'

    games_bar = build_games_bar(session_id, games, game, player)
    players_panel  = build_players_panel(session_id, players, game, player)

    return HTMLResponse(charts_html + games_bar + players_panel)

def build_games_bar(session_id, games, active_game, player):
    def btn(label, game_value):
        active = "active" if game_value == active_game else ""
        url = f"/charts/{session_id}?game={game_value}&player={player}"
        return f"""
        <button class="selector-btn {active}"
            hx-get="{url}"
            hx-target="#chart-area"
            hx-swap="innerHTML"
            hx-indicator="#loading">
            {label}
        </button>
        """

    buttons = btn("All Games", "All")
    for g in games:
        buttons += btn(g, g)

    return f"""
    <div id="games-bar"
         class="team-bar"
         hx-swap-oob="true">
        {buttons}
    </div>
    """

def build_players_panel(session_id, players, game, active_player):
    def pbtn(name, extra_class=""):
        active = "active" if name == active_player else ""
        url    = f"/charts/{session_id}?game={game}&player={name}"
        return f"""
        <button class="selector-btn {extra_class} {active}"
            hx-get="{url}"
            hx-target="#chart-area"
            hx-swap="innerHTML"
            hx-indicator="#loading">
            {name}
        </button>
        """

    team_button    = pbtn("Team", "team-btn")
    player_buttons = "".join(pbtn(p) for p in players)

    return f"""
    <aside id="players-panel"
           class="selector-panel"
           hx-swap-oob="true">

        {team_button}

        <div class="selector-divider"></div>

        <div class="selector-group">
            <div class="selector-label">PLAYERS</div>
            {player_buttons}
        </div>

    </aside>
    """

def sidebar_html(session_id, games, players, warnings, active_game, active_player):
    warn_html = ""
    if warnings:
        items = "\n".join(f"<li>{w}</li>" for w in warnings)
        warn_html = f"""
        <div class="warnings-block">
          <div class="warn-title">⚠ WARNINGS</div>
          <ul class="warn-list">{items}</ul>
        </div>
        """

    games_bar = build_games_bar(
        session_id, games, active_game, active_player
    ).replace('hx-swap-oob="true"', "")

    players_panel = build_players_panel(
        session_id, players, active_game, active_player
    ).replace('hx-swap-oob="true"', "")

    return f"""
    {warn_html}

    {games_bar}

    <div class="workspace">
        {players_panel}

        <section class="chart-section">
            <div id="chart-area" class="chart-area"
                 hx-get="/charts/{session_id}?game={active_game}&player={active_player}"
                 hx-trigger="load"
                 hx-swap="innerHTML">
                <p class="loading-pulse">Loading…</p>
            </div>
        </section>
    </div>
    """

if __name__ == "__main__":
    import uvicorn
    uvicorn.run("main:app", host="0.0.0.0", port=8000, reload=True)
